version: '3.8'
services:
  backend:
    build: ./backend
    ports: ["5000:5000"]
    env_file: .env
    volumes: 
      - "./backend:/usr/src/app"
      - "/usr/src/app/node_modules" # Preserve node_modules from build
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    volumes:
      - "./frontend:/usr/src/app"
      - "/usr/src/app/node_modules" # Preserve node_modules from build
  redis:
    image: redis:alpine